package Governance::Engine::Model::DBIC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'create=static',
    
    connect_info => {
        dsn      => Governance::Config->get('db')->{dsn},
        user     => Governance::Config->get('db')->{user},
        password => Governance::Config->get('db')->{password},
    }
);

=head1 NAME

Governance::Engine::Model::DBIC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Governance::Engine>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<create=static>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.62

=head1 AUTHOR

Shantanu Bhadoria

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
